apiVersion: v1
kind: Service
metadata:
  name: postgres-payload-example-ecommerce
  namespace: payload-example-ecommerce
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
