# nginx-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: example-1
  name: nginx-homepage
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <title>example-1</title>
        <style>
            body {font-family: sans-serif;background-color: #282c34;color: #2f599f;display: flex;justify-content: center;align-items: center;height: 100vh;margin: 0;}           
            h1 {color: #61dafb;}</style>
    </head>
    <body>
    <h1>example 1</h1>
    <p>sensepitch</p>
    </body>
    </html>