# sensepitch-service.yaml
apiVersion: v1
kind: Service
metadata:
  namespace: example-1
  name: sensepitch-service
spec:
  type: NodePort # This type exposes the service on the node's IP
  selector:
    app: sensepitch-proxy # Selects our Sensei-Pitch pod
  ports:
    - protocol: TCP
      port: 17443
      targetPort: 17443